[workspace]
resolver = "3"
members = ["app", "client"]

[package]
name = "hy4-predict"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
app = { path = "app" }
sails-rs = "0.10.3"

[build-dependencies]
app = { path = "app" }
sails-rs = { version = "0.10.3", features = ["build"] }

[dev-dependencies]
sails-rs = { version = "0.10.3", features = ["gtest"] }
app = { path = "app" }
