#![cfg_attr(target_arch = "wasm32", no_std)]

// Re-export Gear wasm entry points (init / handle / handle_reply / state)
// generated by the #[program] macro when compiling for wasm32 target.
#[cfg(target_arch = "wasm32")]
pub use app::wasm::*;

// Include the compiled wasm binary bytes for use in gtest and clients.
#[cfg(not(target_arch = "wasm32"))]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));
